spring:
  application:
    name: coupon-gateway
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/
zuul:
  # 网关前缀
  prefix: /imooc
  routes:
    # 优惠券模板微服务路由配置定义
    template:
      path: /coupon-template/**
      serviceId: coupon-template
      # 是否需要跳过前缀
      strip-prefix: false
    # 优惠券分发微服务配置定义
    distribution:
      path: /coupon-distribution/**
      serviceId: coupon-distribution
      strip-prefix: false
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 600000
ribbon:
  ConnecTimeout: 15000
  ReadTimeout: 15000
