server:
  port: 7002
  servlet:
    context-path: /coupon-distribution

spring:
  application:
    name: coupon-distribution
  cloud:
    loadbalancer:
      # 开启ribbon 重试机制，即获取服务失败是否从另外一个节点重试
      retry:
        enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false
    database: mysql
  datasource:
    url: jdbc:mysql://35.200.22.61:3306/imooc_coupon_data?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&serverTimezone=UTC&useSSL=false
    username: root
    password: xxx123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接池配置
    druid:
      # 初始话大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间 单位毫秒
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: select 'x'
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙, 'logback'为系统日志框架
      filters: stat,wall,slf4j
      ## 监控配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: \*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*
      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
      ## 配置StatFilter 慢SQL记录
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 1000
  redis:
    host: 35.200.22.61
    port: 6379
    database: 0
    password: 123456
    timeout: 10000ms
    # lettuce 连接池
    lettuce:
      pool:
        # 连接池最大连接数(使用负数标识没有限制)
        max-active: 8
        # 连接池最大阻塞等待时间(使用负数标识没有限制)
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
  kafka:
    bootstrap-servers:
      - 35.200.22.61:9092
    consumer:
      group-id: imooc-coupon-x
      # 从最后一条消费
      auto-offset-reset: latest
eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

# feign 相关配置
feign:
  hystrix:
    # Hystrix 默认是关闭的
    enabled: true
  client:
    config:
      # 全局
      default:
        # 默认的连接超时时间是 10s
        connectTimeout: 2000
        readTimeout: 5000
      # 针对 coupon-template 服务单独配置
      coupon-template:
        connectTimeout: 3000
        readTimeout: 5000
# ------------------------------------ Hystrix -----------------------------------------------
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000

# ----------------------------------------
management:
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    name: imooc-coupon-distribution
    groupId: imooc-coupon-service
    version: 1.0-SNAPSHOT

# ----------------------------------
logging:
  level:
    root: info
    com.imooc.coupon: debug
